# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cannyedge.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61nnyedge.proto\"k\n\x12\x44\x65tectEdgesRequest\x12\"\n\x0bimage_chunk\x18\x01 \x01(\x0b\x32\x0b.ImageChunkH\x00\x12!\n\nparameters\x18\x02 \x01(\x0b\x32\x0b.ParametersH\x00\x42\x0e\n\x0crequest_data\"\x1d\n\nImageChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"8\n\nParameters\x12\x14\n\x0cminThreshold\x18\x01 \x01(\x05\x12\x14\n\x0cmaxThreshold\x18\x02 \x01(\x05\"*\n\x13\x44\x65tectEdgesResponse\x12\x13\n\x0bimage_chunk\x18\x01 \x01(\x0c\x32Q\n\x11\x43\x61nnyEdgeDetector\x12<\n\x0b\x44\x65tectEdges\x12\x13.DetectEdgesRequest\x1a\x14.DetectEdgesResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cannyedge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DETECTEDGESREQUEST']._serialized_start=19
  _globals['_DETECTEDGESREQUEST']._serialized_end=126
  _globals['_IMAGECHUNK']._serialized_start=128
  _globals['_IMAGECHUNK']._serialized_end=157
  _globals['_PARAMETERS']._serialized_start=159
  _globals['_PARAMETERS']._serialized_end=215
  _globals['_DETECTEDGESRESPONSE']._serialized_start=217
  _globals['_DETECTEDGESRESPONSE']._serialized_end=259
  _globals['_CANNYEDGEDETECTOR']._serialized_start=261
  _globals['_CANNYEDGEDETECTOR']._serialized_end=342
# @@protoc_insertion_point(module_scope)
